export enum ContentType {
  JSON = "application/json",
  HTML = "text/html",
  XML = "application/xml",
  TEXT = "text/plain",
  FORM = "application/x-www-form-urlencoded",
  MULTIPART = "multipart/form-data",
  PDF = "application/pdf",
  CSV = "text/csv",
  JPEG = "image/jpeg",
  PNG = "image/png",
  GIF = "image/gif",
  SVG = "image/svg+xml",
  MP4 = "video/mp4",
  MP3 = "audio/mpeg",
  OCTET_STREAM = "application/octet-stream",
  JAVASCRIPT = "application/javascript",
  CSS = "text/css",
  YAML = "application/x-yaml",
  RSS = "application/rss+xml",
  ATOM = "application/atom+xml",
  BSON = "application/bson",
  MSGPACK = "application/msgpack",
  MSGPACK5 = "application/x-msgpack",
  BSON5 = "application/x-bson",
}
